name: Deploy Vuepress

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1

      - name: Install lint-md-cli
        run: npm install -g lint-md-cli

      - name: Fix Chinese Copywriting
        run: for MARKDOWN in $(find docs/ -name "*.md"); do lint-md $MARKDOWN; donegit

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist